# Site settings
title: John Choque
description: 'This is personal blog.'
baseurl: ""
url: "http://yongt9412.com"
paginate: 5
# comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : pretty
#permalink : /:title/

# Author info
author:
  name     : 'John Choque'
  url      : http://yongt9412.github.io
  facebook : http://facebook.com/yongt9412
  twitter  : http://twitter.com/yongt9412

#github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "yongt9412"
#google_analytics: UA-52446115-1
